name: Merge and Upload Cards CDB to CDB-MERGES

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge script with token
        env:
          GH_TOKEN: ${{ secrets.CDB_TOKEN }}  # Pasar el token como variable de entorno
        run: |
          python scripts/merge_cdb.py







